spring:
  application:
    name: springboot-mybatis
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 123456
    url: jdbc:postgresql://localhost:5432/springboot
    username: weilinxi
server:
  port: 8080

